export const style = {
  card: {
    backgroundColor: '#f2e6d9',
    border: 'none',
    borderRadius: '15px',
    padding: '20px',
    margin: '20px auto',
    boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
    textAlign: 'left',
    maxWidth: '300px',
    fontFamily: 'Arial, sans-serif',
  },
  title: {
    color: '#8b7355',
    fontSize: '1.2rem',
    fontWeight: 'bold',
    marginBottom: '15px',
  },
  info: {
    color: '#8b7355',
    marginBottom: '10px',
    fontSize: '0.9rem',
  },
  button: {
    padding: '8px 16px',
    backgroundColor: '#fff9e6',
    color: '#8b7355',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 'bold',
    marginTop: '10px',
  },
};